version: '3'

services:

  postgres:
    image: postgres:latest

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

    ports:
      - 5432:5432

    restart: always

  redis:
    image: redis:latest

    environment:
      - REDIS_PASSWORD=redis@123

    ports:
      - 6379:6379

    restart: always


